### ISSUE TITLE
Alignement on Mac is not quite well

### ISSUE THREAD

**Issue by lylex** [liamg/aminal#103]
**Describe the bug**
When I have lots of files on mac, and use `ls` in aminal terminal, it does not give me a good alignement.

**To Reproduce**
1. Go to aminal terminal
2. Run `mkdir test && cd $_; touch test{1..20}.txt`
3. Run `ls`
4. We can see the bad alignement

**Expected behavior**
It should show a good alignement.

**Screenshots**
```
bash-3.2$ ls
test1.txt    test11.txt  test13.txt  test15.txt  test17.txt  test19.txt  test20.txt  test4.txt test6.txt   test8.txt
test10.txt test12.txt    test14.txt  test16.txt  test18.txt  test2.txt test3.txt   test5.txt   test7.txt   test9.txt
bash-3.2$ 
```

**Environment (please complete the following information):**
 - OS + Version: mac 10.12.6
 - Go Version: go version go1.11.2 darwin/amd64
 - Shell : /bin/bash

**Comment by liamg** [comment]
Thanks, my tab calc was way off, it was tabbing `4 - x` spaces instead of `x` 🤦‍♂️
