### ISSUE TITLE
Mac OS: black window after start

### ISSUE THREAD

**Issue by vkravets** [liamg/aminal#108]
**Describe the bug**
On my Mac OS after start aminal black window is appeared, nothing happens during key press, mouse hover etc... The workaround to get content at window to perform resize of the window, after it working as expected.... it seems appeared issue with init or init render at OpenGL stuck 

**To Reproduce**
1. Run aminal at macOs
2. Look at the window 

**Expected behavior**
Window with terminal appeared

**Environment (please complete the following information):**
 - OS + Version: macOS 10.1.4.1
 - Go Version: go1.11.2
 - Shell: fish

**Comment by vkravets** [comment]
<img width="804" alt="screen shot 2018-12-04 at 10 56 13" src="https://user-images.githubusercontent.com/985336/49430379-89ecbc00-f7b3-11e8-9e0e-4dcdf1fee8b6.png">

**Comment by liamg** [comment]
I have a workaround for this, I'll PR later today.
