### ISSUE TITLE
Problem with Zap library

### ISSUE THREAD

**Issue by LukeB42** [liamg/aminal#15]
```
$ go build -v
src/go/aminal
# src/go/aminal
./main.go:120:26: cannot use logger (type *"go.uber.org/zap".SugaredLogger) as type *"github.com/liamg/aminal/vendor/go.uber.org/zap".SugaredLogger in argument to terminal.New
./main.go:122:14: cannot use logger (type *"go.uber.org/zap".SugaredLogger) as type *"github.com/liamg/aminal/vendor/go.uber.org/zap".SugaredLogger in argument to gui.New
```

**Comment by liamg** [comment]
It looks very much like your `$GOPATH` is not set up correctly, which is required atm. [This](https://github.com/golang/go/wiki/SettingGOPATH) should help.

**Comment by rochana-atapattu** [comment]
I'm getting the same error 

> go version go1.13.4 linux/amd64
> /home/rochana/work

Excuse me if this sounds dumb, I'm very new to go.
But how can it be a GOPATH issue it seems like a type mismatch?
