### ISSUE TITLE
Windows icon goes super small when disconnecting external 4k monitors

### ISSUE THREAD

**Issue by daviesalex** [liamg/aminal#158]
**Describe the bug**
I am not 100% sure why this happens, but I regularly dock and undock my Windows 10 1809 laptop from a external monitor. Sometimes the icons for both putty and aminal (but nothing else, including Hyper, Office, Spotify, Chrome) go super small - see screenshot (far right is aminal, one to the left of it putty):

![image](https://user-images.githubusercontent.com/1106249/51427893-dde12200-1bf4-11e9-868d-6943a7d39196.png)

**Comment by MaxRis** [comment]
Was not able to repro the issue, but Thomas's observation makes sense. Have update the icon ( https://github.com/liamg/aminal/pull/200 ) with 128x128 one

**Comment by MaxRis** [comment]
@daviesalex could you please confirm that this issue doesn't appear anymore, thanks

**Comment by daviesalex** [comment]
I think this is now resolved. Please close - I can reopen if I can repro.
