### ISSUE TITLE
Port vttest tst_movements to unit test

### ISSUE THREAD

**Issue by rrrooommmaaa** [liamg/aminal#160]
**Is your feature request related to a problem? Please describe.**
Automate vttest test 1 (cursor movements) testing

**Describe the solution you'd like**
The simplest way to test cursor movements (vttest test 1) is to port tst_movements() function to a unit test in Go 

**Describe alternatives you've considered**
Running vttest as application

**Comment by nikitar020** [comment]
This issue was fixed by PR https://github.com/liamg/aminal/pull/209, isn't it?

**Comment by rrrooommmaaa** [comment]
@nikitar020 Probably so
