### ISSUE TITLE
htop resizing issue

### ISSUE THREAD

**Issue by rrrooommmaaa** [liamg/aminal#167]
**Describe the bug**
When htop is launched, it shows (almost) blank screen until window is resized

**To Reproduce**
1. Start `aminal`
2. Launch `htop`
3. See error
4. Drag window's corner
5. Everything is fine

**Expected behavior**
`htop` should be displayed correctly right after the start

**Environment (please complete the following information):**
 - OS + Version: Ubuntu 18.04, MacOS
 - Go Version: 1.10.4
 - Shell: Bash

**Comment by liamg** [comment]
Fixed in `v0.8.9`
