### ISSUE TITLE
vim not working, Unknown OSC/CSI control sequence errors are printed

### ISSUE THREAD

**Issue by diamondburned** [liamg/aminal#174]
Description: `vim` isn't drawn, error codes are dumped into console

Reproducing:
1. Run `vim`
2. See error

Expected behavior: vim actually rendering

Screenshot: https://ptpb.pw/saB9.png

Environment:
 - OS + version: Arch Linux
 - GPU: Nvidia GT1030 driver version 415.25
 - Go version: `go1.11.4 linux/amd64`
 - Shell: `bash`

Logs: https://0x0.st/sCWf.log

**Comment by liamg** [comment]
Apologies, this was an issue with 0.8.8 - this is fixed in `v0.8.9`
