### ISSUE TITLE
Should send 0x7f instead of 0x08 for backspace (in some cases)

### ISSUE THREAD

**Issue by mjs** [liamg/aminal#178]
**Describe the bug**

Backspace doesn't work when zsh is in use.

**To Reproduce**
1. Run aminal with the shell set to `zsh`.
2. Type some text.
3. Hit backspace.
4. Text is not removed.
5. Close aminal.
6. Run aminal with the shell set to `bash`.
7. Type some text.
8. Hit backspace.
9. Text is removed.

Backspace in zsh works fine with gnome-terminal on the same machine.

**Expected behavior**

Text to should be removed when backspace is used with zsh.

**Environment (please complete the following information):**
 - OS + Version: Ubuntu 16.04
 - Go Version - 1.11.5
 - Shell - zsh 5.1.1 

**Logs**

`aminal --debug` produces logs but there are no logs generated when backspace is pressed.

**Comment by klamonte** [comment]
FYI -- VT220 defines the key located where we typically see backspace as "delete" which sends ASCII DEL (0x1F).  This convention is also used by linux console and many xterm configs.  VT100/102 OTOH have both backspace which sends BS (0x08) and delete which sends DEL.

Most "xterm"s I have seen use DEL for backspace, it is probably a better default than BS.

**Comment by mjs** [comment]
@klamonte thanks for confirming. I think you mean DEL is 0x7f though, not 0x1f right?

https://www.asciihex.com/character/control/127/0x7F/del-delete-character

**Comment by MaxRis** [comment]
Have moved Issue's card into In-Progress column https://github.com/liamg/aminal/projects/2

**Comment by klamonte** [comment]
@mjs yes that was an unfortunate typo, I did mean 0x7F and not 0x1F.

**Comment by mjs** [comment]
This has been fixed
