### ISSUE TITLE
Please make sure key binding and mappings done with autohotkey on Windows are respected.

### ISSUE THREAD

**Issue by cjw296** [liamg/aminal#196]
**Is your feature request related to a problem? Please describe.**

I use autohotkey scripts to try and make a Windows keyboard feel more like a Mac one.

**Describe the solution you'd like**

Please make sure Aminal uses the post-auto-hotkey keys.

**Describe alternatives you've considered**

None.

**Additional context**

Most stuff on Windows gets the post hotkey-manipulated keys, Powershell and Chrome are two annoying exceptions, so please don't do whatever they do ;-)

**Comment by mjs** [comment]
Moved to https://github.com/jumptrading/waminal/issues/3
