### ISSUE TITLE
"Screen feature" 11th subtest of vttest fails to render text line aligned to bottom of screen

### ISSUE THREAD

**Issue by MaxRis** [liamg/aminal#207]
**Describe the bug**
11th subtest of "Screen features" test suite of vttest fails to render correctly text line aligned to the bottom of terminal screen.

**To Reproduce**
1. Run vttest
2. Enter 2 and press ENTER
3. Navigate to the 11th screen

**Expected behavior**
![expected](https://user-images.githubusercontent.com/1928902/52526006-1091ae00-2cbb-11e9-9e7b-b8039d30db5b.png)

**Current wrong behavior**
![test-screen-features-11](https://user-images.githubusercontent.com/1928902/52525986-dde7b580-2cba-11e9-9d0e-4dbce857a27b.png)

**Environment (please complete the following information):**
 - OS + Version: Ubuntu 1804

**Comment by rrrooommmaaa** [comment]
@MaxRis This is the logical "bottom of screen". If you stretch `xterm` vertically (before launching `vttest`) to match aminal's initial dimensions, you'll see the same (see screenshot). `vttest` doesn't seem to modify the height of the screen, nor obtain actual dimensions.
![screenshot from 2019-02-15 21-35-37](https://user-images.githubusercontent.com/23335944/52877145-3f4fce80-316a-11e9-966c-6ae7190e9c83.png)

**Comment by MaxRis** [comment]
@rrrooommmaaa you're right, thank you for finding this out!
