### ISSUE TITLE
"quick connect" dialog for launching shells

### ISSUE THREAD

**Issue by cjw296** [liamg/aminal#252]
**Is your feature request related to a problem? 
maOS Terminal has an way of launching new shells: Apple-Shift-K brings up the "New Remote Connection" dialog, I think Aminal can learn from that and do better. Currently, we need to launch some existing shell start new shells, and I have to remember a bunch of command line options.

**Describe the solution you'd like**

Ctrl-Shift-N (or K, keybindings need to be configurable) to bring up a dialog with a search box and a selection wizard.

The search will search through previously used shells/remote connections, if none are found you can just type the whole shell command. This might even example out to the whole aminal command to launch.

The selection wizard will navigate you through the process:

What type of shell do you want? 
- cmd.exe (Windows)
- powershell (Windows)
- bash (Mac/Linux)
- mosh (all platforms)
- ssh (all platforms)
- docker (all platforms)

Where a shell needs more info to continue, ask for it:
- for mosh and ssh, the remote host name should be typable but also allow picking from recently used hostnames
- docker would let you pick the image name and add any extra options, eg: 
   `docker run -it .../library/rhel7 bash`
- other shell methods may need other options?

**Describe alternatives you've considered**

Typing in a shell to to launch Aminal is a real blocker to uptake.

**Additional context**

https://github.com/liamg/aminal/issues/205 should not be incompatible with this, and all urls should map nicely to choice of shell along with parameters required to launch them.

This will likely need lots of polishing over time, but if we can get something started we can then start getting more feedback on how we'd like things to work.

**Comment by mjs** [comment]
Moved to https://github.com/jumptrading/waminal/issues/1
