### ISSUE TITLE
get "docker run -it" working as a shell

### ISSUE THREAD

**Issue by cjw296** [liamg/aminal#253]
```
C:\Users\cwithers\Downloads>aminal-windows-amd64.exe --shell "docker run -it quay.w2k.jumptrading.com/library/rhel7 bash" 
1.5505905844262707e+09  info    aminal/main.go:32       Allocating pty... 
1.550590584685676e+09   info    aminal/main.go:58       Creating terminal... 
1.5505905857886848e+09  info    gui/gui.go:683  OpenGL version 4.6.0 NVIDIA 411.81 
```

It didn't crash, but it doesn't look like it wired it up right as I just got an empty aminal shell window.
The container is running, though, and it didn't go away when I killed aminal.

I have a feeling that this has happened with some other shells people have tried, so I suspect fixing this will fix a class of issues we've seen.

**Comment by cjw296** [comment]
Yay! This is exciting! Can you point me at the first nightly windows build where this is fixed so I can test?

**Comment by nikitar020** [comment]
@cjw296 It is included in this build: https://github.com/liamg/aminal/releases/tag/Nightly-develop-2019-03-19-000e763
