### ISSUE TITLE
page up/down do not work

### ISSUE THREAD

**Issue by liamg** [liamg/aminal#33]

**Comment by tetafro** [comment]
The same for me. `PgUp`, `PgDown`, `Home`, `End` give me `~`.
Also not sure about other shortcuts like `ALT`+`Backspace` for deleting a word - does aminal got something like this?

Aminal version: 0.7.8
OS + Version: Linux Mint 19
Go Version: 1.10 linux/amd64
Shell: Bash

**Comment by liamg** [comment]
I've fixed the home button, this was simply broken.

However, PgUp/PgDown are different - the keypress is forwarded on to the shell correctly as far as I can see. It actually seems to behave the same as iTerm2 when I use these keys.

And as for alt-backspace, I just need to figure out the escape we should send to the shell when this is pressed, we're currently not modifying backspace presses at all with modifier keys.

**Comment by liamg** [comment]
I've added `alt+backspace` support now too.
