### ISSUE TITLE
Customize web search target

### ISSUE THREAD

**Issue by p3lim** [liamg/aminal#78]
**Is your feature request related to a problem? Please describe.**
The "google" hotkey target URL is hard-coded, it should be customizable and probably generalized.

**Describe the solution you'd like**
Change this URL to a configuration option:
https://github.com/liamg/aminal/blob/7da69c342c499bb10102593b3751e23ffd1dcb56/gui/actions.go#L37

Also, maybe generalize the configuration options from "google" to "web search".

**Comment by liamg** [comment]
Yep, good call, thanks for the request.  I'll sort this out tonight.

**Comment by liamg** [comment]
You can now do this with the `search_url` config item. See the README for more info.

I'll merge it to master shortly, there's currently a partial outage on CircleCI...
