### ISSUE TITLE
Control characters don't follow keyboard layout

### ISSUE THREAD

**Issue by japanoise** [liamg/aminal#82]
**Describe the bug**
When trying to close aminal with `^D`, and playing around with other control characters, I noted that despite using a Dvorak keyboard, and typing working correctly, control characters came out as if typed on a QWERTY layout.

**To Reproduce**
1. Switch keyboard layout to Dvorak
2. Open aminal
3. Verify keyboard was changed to dvorak by pressing the `asdf` keys; it should come out as `aoeu`
4. Navigate to the middle of the line with the arrow keys
5. Press `^U` (control-U)
6. Cursor will move forward as if `^F` was pressed.

**Expected behavior**
Line should either be deleted in its entirety or to the start of line (shell dependent).

**Environment (please complete the following information):**
 - OS + Version: Ubuntu 18.04.1 LTS (Bionic Beaver)
 - Go Version: go version go1.10.4 linux/amd64
 - Shell [e.g. Bash/Zsh]: zsh

**Additional context**
This happens in other programs when the physical location of the key is used rather than the actual character emitted; the latter takes layout into account.

**Logs**
Typing "testaoeu" as expected on dvorak, arrow-ing to the middle of the line, pressing what I'd expect to be `^U` and what is actually being treated as `^U`, then exiting.

http://dpaste.com/00HKKJM or http://sprunge.us/G5vSL0

**Comment by iNode** [comment]
Have the same issue with colemak keyboard layout as well.

**Comment by liamg** [comment]
Should be sorted now, tested with a couple of layouts.

**Comment by japanoise** [comment]
Works for me, thank you for the quick turnaround.
